\c  dev_bakery;


INSERT INTO cakes (name, price, description, image, is_favorite) VALUES
 ('Tarta Mousse Chocolate',24, 'Fina base de bizcocho con una ganache de chocolate recubierto de una exquisita mousse de chocolate puro.', 'https://bonifaciobakery.netlify.app/images/tarta-mousse-chocolate.png', TRUE),
('Tarta de Fresas', 24, 'Finas capas de bizcocho acompañadas de una capa de crema pastelera,  nata montada natural y mermelada de fresa, todo ello decorado con nata y fresas naturales.','https://bonifaciobakery.netlify.app/images/tarta-de-fresas.png', TRUE), ('Tarta de Sara', 24, 'Cuenta que Sarah Bernhadrt era una actriz francesa de teatro y cine, incluso se consideraba la más importante del siglo XIX y la mas famosa de la historia. Tanto fue la fama que alcanzó que inspiró la creación de este delicioso postre que ahora lleva por nombre tarta Sara. Este pastel esta formado por un esponjoso bizcocho genovés, empapado en almíbar y esta relleno y cubierto por una crema de mantequilla. Además está decorado con almendra laminada y cerezas.', 'https://bonifaciobakery.netlify.app/images/sara.png', TRUE),('Tarta de Zanahoria', 24,'Capas de bizcocho  elaborado a base de harina integral, azúcar moreno y zanahoria con un toque de canela, acompañadas de crema de queso rebajado con nata. Una explosión perfecta de sabores en tu boca.','https://bonifaciobakery.netlify.app/images/tarta-zanahoria.png', TRUE),('Tarta de Septembre', 70, 'Capas de piononos o bizcochos de vainilla rellenos de crema de chocolate, y fresa espcial de Septembre','https://bonifaciobakery.netlify.app/images/speciality-cake.png', TRUE);


INSERT INTO minis (name, price, description, image, is_favorite) VALUES

('Napolitana de chocolate', 2, 'Napolitana de hojaldre con relleno de crema de chocolate y virutas de chocolate por encima', 'https://medbar.es/wp-content/uploads/2018/08/Napolitana-chocolate.png', TRUE), ('Caracola',2,'Nuestra caracola esta hecha con crema pastelera untuosa, gramaje generoso, numerosas pasas azucaradas de forma natural y un hojaldrado ligero y crujiente. Todas las mañanas es horneada por nuestros maestros panaderos.','https://bonifaciobakery.netlify.app/images/caracol.png', FALSE), ('Napolitana de crema', 2,'Riquísima napolitana de hojaldre rellena con crema pastelera. Horneada cada mañana por nuestros panaderos.' ,'https://angellinares.es/137334-large_default/napolitana-magno-crema-140g.jpg', TRUE), ('Palmeritas de Chocolate', 2 ,'Todos los días nuestros maestros panaderos elaboran estas riquísimas palmeritas de hojaldre y las bañan en rico chocolate fundido, después las enfrían y dan toque a estas delicias de chocolate.', 'https://bonifaciobakery.netlify.app/images/palmera-chocolate.png', FALSE), ('Croissants Rellenos', 3, 'Horneados a diario nuestros croissants los puedes elegir de: Pavo y queso, Salmón con huevo duro y queso, Cangrejo con salsa rosa, Vegetal con atún y huevo,
Atún, cebolla y mahonesa','https://toast-local-nyc3-production.nyc3.cdn.digitaloceanspaces.com/restaurants/3986b31d-c177-49f9-8a29-2e6d3cba5204/croissant-hamcheese-menuitem-346955-1198.webp', TRUE); 